### PR TITLE
Sustainer stage mass recalculation

### PR DESCRIPTION
**Pull request by Noiredd**
Experimental PR in response to #17 - conversation starter, ~do not merge~!

### CODE REVIEW

**Comment by Noiredd** [comment]
Updated the mass recalculation hack with accounting for the changed `maxT` in staging system.

**Comment by Patrykz94** [comment]
This one works correctly.

I attached the craft, boot and mission files in case you want to do some more testing on it.

It uses RP-0, Procedural Parts, Procedural Fairings and Procedural Avionics. If there are any problems with it, let me know but I didn't notice any other mod parts.

[X-Probe.zip](https://github.com/Noiredd/PEGAS/files/1428952/X-Probe.zip)

**Comment by Noiredd** [comment]
Trying to install RP-0 made my game unusable - good thing I always back up first. Thank you for the help, but it was faster to modify my Atlas V for testing. This allowed me to find one more obstacle: sustainer stages that are additionally g-limited.  
If we recalculate the mass of such stage, we have to recalculate not its burn time, but most importantly: the moment when its acceleration exceeds limit - *and then* recalculate the entire g-limited virtual stage.

**Comment by Noiredd** [comment]
It should be all good now. Care to try the new solution, @Patrykz94?

**Comment by Patrykz94** [comment]
I can test it tomorrow (will need to build a new rocket for the gLimit test) and I'll let you know how it's doing.

**Comment by Noiredd** [comment]
No real need to do the gLimit test, since I consider my Atlas V to have covered it. If you can run your X-Probe with this, then I feel confident this is good.

**Comment by Patrykz94** [comment]
@Noiredd Just tested and it's working like advertised 👍

**Pull request merged**
